#!/usr/bin/env node
// Concatenates src/ into one self-contained index.html.
//
// The browser cannot fetch ES modules over file://, and the Artifact CSP blocks
// every external request, so the app ships as a single inline module script.
// Stripping the import/export lines is safe because the modules are listed in
// dependency order and share one scope with no name collisions.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const read = (...parts) => readFileSync(join(root, ...parts), 'utf8');

export const MODULES = [
  'format.js',
  'derive.js',
  'color.js',
  'catalog.js',
  'render.js',
  'runtime.js',
  'generate.js',
  'state.js',
  'ui-export.js',
  'ui.js'
];

const IMPORT_LINE = /^import\s[^;]*?from\s*['"][^'"]*['"];?[ \t]*\r?\n?/gm;
const EXPORT_KEYWORD = /^export\s+/gm;

export function stripModuleSyntax(source) {
  return source.replace(IMPORT_LINE, '').replace(EXPORT_KEYWORD, '');
}

export function buildBundle() {
  const payload = read('sample-payload.json').trim();
  const parts = [
    '// Generated by build.js. Edit the files in src/ instead of this bundle.',
    'const SAMPLE_PAYLOAD = ' + payload + ';'
  ];
  for (const name of MODULES) {
    parts.push('// ---------- src/' + name + ' ----------\n' + stripModuleSyntax(read('src', name)).trim());
  }
  return parts.join('\n\n');
}

export function buildHtml() {
  const bundle = buildBundle();
  const css = read('src', 'app.css').trim();
  return read('src', 'index.template.html')
    .replace('/*CSS*/', () => '\n' + css + '\n')
    .replace('/*BUNDLE*/', () => '\n' + bundle + '\n');
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const html = buildHtml();
  writeFileSync(join(root, 'index.html'), html);
  const kb = (Buffer.byteLength(html, 'utf8') / 1024).toFixed(1);
  console.log('index.html geschrieben — ' + kb + ' kB, ' + MODULES.length + ' Module');
}
