// The export formats: a runnable script, a handover prompt, and a config file —
// plus the readers that turn any of those back into a config.

import { RUNTIME_SOURCE } from './runtime.js';
import { CATALOG_BY_ID, isBlock } from './catalog.js';
import { DEFAULT_SEPARATOR } from './render.js';

const SEGMENT_KEYS = [
  'id', 'label', 'emoji', 'source', 'format', 'showLabel', 'showEmoji',
  'line', 'color', 'hideValues', 'scaleMap', 'bold', 'dim', 'group'
];

export const DEFAULT_INSTALL_PATH = 'C:/Users/marku/.claude/statusline.js';
export const MAX_LINES = 3;

export function normaliseConfig(config) {
  const c = config || {};
  const separator = c.separator === undefined ? DEFAULT_SEPARATOR : c.separator;
  const given = Array.isArray(c.separators) ? c.separators : [];
  const separators = [];
  for (let i = 0; i < MAX_LINES; i++) {
    separators.push(typeof given[i] === 'string' ? given[i] : separator);
  }

  return {
    version: 2,
    separator,
    separators,
    dimSeparator: c.dimSeparator !== false,
    lineCount: Math.max(1, Math.min(MAX_LINES, Number(c.lineCount) || 1)),
    segments: (c.segments || []).map(segment => {
      const out = {};
      for (const key of SEGMENT_KEYS) {
        if (segment[key] !== undefined) out[key] = segment[key];
      }
      return out;
    })
  };
}

export function generateScript(config) {
  const cfg = normaliseConfig(config);
  return [
    '#!/usr/bin/env node',
    '// Claude Code status line, generated by the Statusline Builder.',
    '//',
    '// Install by pointing settings.json at this file:',
    '//   "statusLine": { "type": "command", "command": "node <path to this file>" }',
    '//',
    '// Everything configurable lives in CFG below; the engine underneath is generic.',
    '// The builder can read this file back in, so keep the CFG block intact if you',
    '// want to keep editing it there.',
    '',
    'const CFG = ' + JSON.stringify(cfg, null, 2) + ';',
    RUNTIME_SOURCE.trim(),
    ''
  ].join('\n');
}

export function generateConfigJson(config) {
  return JSON.stringify(normaliseConfig(config), null, 2);
}

export function parseConfigJson(text) {
  const parsed = typeof text === 'string' ? JSON.parse(text) : text;
  if (!parsed || typeof parsed !== 'object') throw new Error('Config muss ein Objekt sein.');
  if (!Array.isArray(parsed.segments)) throw new Error('Config braucht ein segments-Array.');

  const segments = parsed.segments.map((segment, index) => {
    if (!segment || typeof segment !== 'object') {
      throw new Error('Segment ' + index + ' ist kein Objekt.');
    }
    // Fall back to the catalogue entry so an abbreviated config still works.
    // Blocks are user-made and have no catalogue entry, so they carry themselves.
    const base = isBlock(segment) ? {} : (CATALOG_BY_ID[segment.id] || {});
    if (!segment.source && !base.source) {
      throw new Error('Segment ' + (segment.id || index) + ' hat keine bekannte Quelle.');
    }
    return { ...base, ...segment };
  });

  return { ...normaliseConfig({ ...parsed, segments }), segments };
}

// Pulls the CFG object literal back out of a generated statusline.js. The
// literal is written with JSON.stringify, so brace matching plus JSON.parse is
// enough — no evaluation of untrusted code.
export function extractCfgLiteral(text) {
  const marker = /const\s+CFG\s*=\s*\{/.exec(String(text));
  if (!marker) return null;

  const source = String(text);
  const start = marker.index + marker[0].length - 1;
  let depth = 0;
  let quote = '';
  let escaped = false;

  for (let i = start; i < source.length; i++) {
    const ch = source[i];
    if (quote) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === quote) quote = '';
      continue;
    }
    if (ch === '"' || ch === "'") { quote = ch; continue; }
    if (ch === '{') depth += 1;
    else if (ch === '}') {
      depth -= 1;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }
  return null;
}

// Accepts a config JSON or a generated statusline.js and returns a config.
export function parseAnyConfig(text) {
  const trimmed = String(text || '').trim();
  if (!trimmed) throw new Error('Nichts zum Einlesen — bitte Datei wählen oder Text einfügen.');

  if (trimmed.startsWith('{')) return parseConfigJson(trimmed);

  const literal = extractCfgLiteral(trimmed);
  if (literal) return parseConfigJson(literal);

  if (/\bjq\b/.test(trimmed) || /^#!.*\b(bash|sh)\b/m.test(trimmed)) {
    throw new Error(
      'Das sieht nach einer Bash-Statusline aus. Die lässt sich nicht automatisch übernehmen — ' +
      'bau die Segmente einmal links zusammen, danach kannst du das erzeugte statusline.js immer wieder laden.'
    );
  }
  throw new Error('Weder eine Config noch ein erzeugtes statusline.js — kein CFG-Block gefunden.');
}

function describeColor(color) {
  if (!color) return 'keine Farbe';
  if (color.mode === 'static') return 'fest ' + color.value;
  if (color.mode === 'threshold') {
    return 'Schwellen ' + (color.stops || []).map(([at, hex]) => at + '→' + hex).join(', ');
  }
  if (color.mode === 'gradient') {
    return 'Verlauf ' + color.from + '→' + color.to + ' über ' + color.min + '–' + color.max;
  }
  return color.mode;
}

function describeFormat(format) {
  const f = format || {};
  const bits = [f.type || 'text'];
  for (const key of ['decimals', 'mode', 'max', 'slice', 'prefix', 'suffix', 'onLabel', 'abbrev']) {
    if (f[key] !== undefined) bits.push(key + '=' + f[key]);
  }
  return bits.join(' ');
}

function describeSource(segment) {
  if (isBlock(segment)) return 'fester Text `' + segment.source.value + '`';
  if (segment.source && segment.source.kind === 'derived') return 'abgeleitet über `' + segment.source.fn + '`';
  return 'Feld `' + (segment.source ? segment.source.path : '?') + '`';
}

export function generatePrompt(config, opts = {}) {
  const cfg = normaliseConfig(config);
  const installPath = opts.installPath || DEFAULT_INSTALL_PATH;

  const lines = [];
  for (let line = 0; line < cfg.lineCount; line++) {
    const onThisLine = cfg.segments.filter(s => (Number(s.line) || 0) === line);
    if (!onThisLine.length) continue;
    lines.push('');
    lines.push('**Zeile ' + (line + 1) + '** — Trenner `' + cfg.separators[line] + '`' +
      (cfg.dimSeparator ? ' (gedimmt)' : ''));
    onThisLine.forEach((s, i) => {
      const parts = [
        (i + 1) + '. `' + s.id + '`',
        describeSource(s),
        'Format: ' + describeFormat(s.format),
        'Farbe: ' + describeColor(s.color)
      ];
      if (s.showEmoji !== false && s.emoji) parts.push('Emoji: ' + s.emoji);
      if (s.showLabel && s.label) parts.push('Label: ' + s.label);
      lines.push('   - ' + parts.join(' · '));
    });
  }

  return [
    'Bitte richte meine Claude Code Statusline ein.',
    '',
    '## Ziel',
    '',
    'Ein Node-Skript unter `' + installPath + '`, das den Statusline-JSON-Payload von stdin liest',
    'und die unten beschriebene Zeile ausgibt. Kein `jq`, keine Dependencies — nur Node.',
    'Danach `~/.claude/settings.json` eintragen:',
    '',
    '```json',
    '"statusLine": { "type": "command", "command": "node ' + installPath + '" }',
    '```',
    '',
    '## Aufbau',
    '',
    '- Zeilen: ' + cfg.lineCount + ', jede mit eigenem Trenner (siehe unten)',
    '- Segmente in genau dieser Reihenfolge:',
    ...lines,
    '',
    '## Regeln',
    '',
    '- Fehlt ein Feld im Payload, entfällt das Segment stillschweigend — niemals `null` oder leere Slots drucken.',
    '- Segmente mit fester Quelle (`fester Text`) werden immer gedruckt, sie dienen als Blocktrenner.',
    '- `resets_at` kann Epoch-Sekunden, Millisekunden oder ISO-String sein; alle drei abfangen.',
    '- Es gibt nur die Buckets `rate_limits.five_hour` und `rate_limits.seven_day`.',
    '- Farben als Truecolor (`ESC[38;2;r;g;bm`), am Ende jedes Segments zurücksetzen.',
    '- Das ganze Rendering in try/catch; im Fehlerfall nur Modell und Verzeichnis ausgeben.',
    '',
    '## Fertige Konfiguration',
    '',
    'Falls du sie direkt übernehmen willst — das ist exakt die Config, die mein Builder erzeugt hat:',
    '',
    '```json',
    generateConfigJson(cfg),
    '```'
  ].join('\n');
}

// ---- installation helpers, per operating system ----

export const OSES = ['windows', 'macos', 'linux'];

export const INSTALL_PATHS = {
  windows: DEFAULT_INSTALL_PATH,
  macos: '~/.claude/statusline.js',
  linux: '~/.claude/statusline.js'
};

export const SHELL_NAMES = { windows: 'PowerShell', macos: 'Terminal', linux: 'Terminal' };

const toWindowsPath = p => String(p).replace(/\//g, '\\');
const toPosixPath = p => String(p).replace(/\\/g, '/');

// A tilde has to survive unquoted or it will not expand, so it becomes $HOME —
// that expands inside double quotes and still tolerates spaces in the path.
function posixTarget(p) {
  const path = toPosixPath(p);
  return path.startsWith('~') ? '"$HOME' + path.slice(1) + '"' : '"' + path + '"';
}

export function shellQuote(path) {
  const p = String(path);
  if (p.startsWith('~')) return p;
  return /\s/.test(p) ? '"' + p + '"' : p;
}

// Writes the clipboard straight into the target file — no download involved.
export function writeToFileCommand(os, installPath) {
  const path = installPath || INSTALL_PATHS[os] || DEFAULT_INSTALL_PATH;
  if (os === 'macos') return 'pbpaste > ' + posixTarget(path);
  if (os === 'linux') return 'xclip -selection clipboard -o > ' + posixTarget(path);
  return 'Get-Clipboard -Raw | Set-Content -Encoding utf8 "' + toWindowsPath(path) + '"';
}

// Prints the first line, which must be the node shebang. A leading brace means
// the config was copied instead of the script.
export function verifyCommand(os, installPath) {
  const path = installPath || INSTALL_PATHS[os] || DEFAULT_INSTALL_PATH;
  if (os === 'windows') return 'Get-Content "' + toWindowsPath(path) + '" -TotalCount 1';
  return 'head -1 ' + posixTarget(path);
}

export function generateSettingsSnippet(installPath, os) {
  const path = installPath || INSTALL_PATHS[os] || DEFAULT_INSTALL_PATH;
  const shown = os === 'macos' || os === 'linux' ? toPosixPath(path) : path;
  return JSON.stringify(
    { statusLine: { type: 'command', command: 'node ' + shellQuote(shown) } },
    null,
    2
  );
}
