// The three export formats: a runnable script, a handover prompt, and a config
// file that can be read back in.

import { RUNTIME_SOURCE } from './runtime.js';
import { CATALOG_BY_ID } from './catalog.js';

const SEGMENT_KEYS = [
  'id', 'label', 'emoji', 'source', 'format', 'showLabel', 'showEmoji',
  'line', 'color', 'hideValues', 'scaleMap', 'bold', 'dim'
];

export const DEFAULT_INSTALL_PATH = 'C:/Users/marku/.claude/statusline.js';

export function normaliseConfig(config) {
  const c = config || {};
  return {
    version: 1,
    separator: c.separator === undefined ? ' | ' : c.separator,
    dimSeparator: c.dimSeparator !== false,
    lineCount: Math.max(1, Math.min(3, Number(c.lineCount) || 1)),
    segments: (c.segments || []).map(segment => {
      const out = {};
      for (const key of SEGMENT_KEYS) {
        if (segment[key] !== undefined) out[key] = segment[key];
      }
      return out;
    })
  };
}

export function generateScript(config) {
  const cfg = normaliseConfig(config);
  return [
    '#!/usr/bin/env node',
    '// Claude Code status line, generated by the Statusline Builder.',
    '//',
    '// Install by pointing settings.json at this file:',
    '//   "statusLine": { "type": "command", "command": "node <path to this file>" }',
    '//',
    '// Everything configurable lives in CFG below; the engine underneath is generic.',
    '',
    'const CFG = ' + JSON.stringify(cfg, null, 2) + ';',
    RUNTIME_SOURCE.trim(),
    ''
  ].join('\n');
}

export function generateConfigJson(config) {
  return JSON.stringify(normaliseConfig(config), null, 2);
}

export function parseConfigJson(text) {
  const parsed = JSON.parse(text);
  if (!parsed || typeof parsed !== 'object') throw new Error('Config muss ein Objekt sein.');
  if (!Array.isArray(parsed.segments)) throw new Error('Config braucht ein segments-Array.');

  const segments = parsed.segments.map((segment, index) => {
    if (!segment || typeof segment !== 'object') {
      throw new Error('Segment ' + index + ' ist kein Objekt.');
    }
    // Fall back to the catalogue entry so an abbreviated config still works.
    const base = CATALOG_BY_ID[segment.id] || {};
    if (!segment.source && !base.source) {
      throw new Error('Segment ' + (segment.id || index) + ' hat keine Quelle.');
    }
    return { ...base, ...segment };
  });

  return { ...normaliseConfig({ ...parsed, segments }), segments };
}

function describeColor(color) {
  if (!color) return 'keine Farbe';
  if (color.mode === 'static') return 'fest ' + color.value;
  if (color.mode === 'threshold') {
    return 'Schwellen ' + (color.stops || []).map(([at, hex]) => at + '→' + hex).join(', ');
  }
  if (color.mode === 'gradient') {
    return 'Verlauf ' + color.from + '→' + color.to + ' über ' + color.min + '–' + color.max;
  }
  return color.mode;
}

function describeFormat(format) {
  const f = format || {};
  const bits = [f.type || 'text'];
  for (const key of ['decimals', 'mode', 'max', 'slice', 'prefix', 'suffix', 'onLabel', 'abbrev']) {
    if (f[key] !== undefined) bits.push(key + '=' + f[key]);
  }
  return bits.join(' ');
}

export function generatePrompt(config, opts = {}) {
  const cfg = normaliseConfig(config);
  const installPath = opts.installPath || DEFAULT_INSTALL_PATH;

  const lines = [];
  for (let line = 0; line < cfg.lineCount; line++) {
    const onThisLine = cfg.segments.filter(s => (Number(s.line) || 0) === line);
    if (!onThisLine.length) continue;
    lines.push('');
    lines.push('**Zeile ' + (line + 1) + '**');
    onThisLine.forEach((s, i) => {
      const parts = [
        (i + 1) + '. `' + s.id + '`',
        s.source && s.source.kind === 'derived'
          ? 'abgeleitet über `' + s.source.fn + '`'
          : 'Feld `' + (s.source ? s.source.path : '?') + '`',
        'Format: ' + describeFormat(s.format),
        'Farbe: ' + describeColor(s.color)
      ];
      if (s.showEmoji !== false && s.emoji) parts.push('Emoji: ' + s.emoji);
      if (s.showLabel && s.label) parts.push('Label: ' + s.label);
      lines.push('   - ' + parts.join(' · '));
    });
  }

  return [
    'Bitte richte meine Claude Code Statusline ein.',
    '',
    '## Ziel',
    '',
    'Ein Node-Skript unter `' + installPath + '`, das den Statusline-JSON-Payload von stdin liest',
    'und die unten beschriebene Zeile ausgibt. Kein `jq`, keine Dependencies — nur Node.',
    'Danach `~/.claude/settings.json` eintragen:',
    '',
    '```json',
    '"statusLine": { "type": "command", "command": "node ' + installPath + '" }',
    '```',
    '',
    '## Aufbau',
    '',
    '- Trennzeichen: `' + cfg.separator + '`' + (cfg.dimSeparator ? ' (gedimmt)' : ''),
    '- Zeilen: ' + cfg.lineCount,
    '- Segmente in genau dieser Reihenfolge:',
    ...lines,
    '',
    '## Regeln',
    '',
    '- Fehlt ein Feld im Payload, entfällt das Segment stillschweigend — niemals `null` oder leere Slots drucken.',
    '- `resets_at` kann Epoch-Sekunden, Millisekunden oder ISO-String sein; alle drei abfangen.',
    '- Es gibt nur die Buckets `rate_limits.five_hour` und `rate_limits.seven_day`.',
    '- Farben als Truecolor (`ESC[38;2;r;g;bm`), am Ende jedes Segments zurücksetzen.',
    '- Das ganze Rendering in try/catch; im Fehlerfall nur Modell und Verzeichnis ausgeben.',
    '',
    '## Fertige Konfiguration',
    '',
    'Falls du sie direkt übernehmen willst — das ist exakt die Config, die mein Builder erzeugt hat:',
    '',
    '```json',
    generateConfigJson(cfg),
    '```'
  ].join('\n');
}

export function generateSettingsSnippet(installPath) {
  return JSON.stringify(
    { statusLine: { type: 'command', command: 'node ' + (installPath || DEFAULT_INSTALL_PATH) } },
    null,
    2
  );
}
